/* Generated By:JavaCC: Do not edit this line. helloConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface helloConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CHAR = 10;
  /** RegularExpression Id. */
  int NUM = 11;
  /** RegularExpression Id. */
  int PLUS = 12;
  /** RegularExpression Id. */
  int MINUS = 13;
  /** RegularExpression Id. */
  int MULT = 14;
  /** RegularExpression Id. */
  int DIV = 15;
  /** RegularExpression Id. */
  int LPAR = 16;
  /** RegularExpression Id. */
  int RPAR = 17;
  /** RegularExpression Id. */
  int SEMI = 18;
  /** RegularExpression Id. */
  int DIGITS = 19;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int INSIDE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<token of kind 6>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 9>",
    "\"a\"",
    "<NUM>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "<DIGITS>",
  };

}
